#!/bin/bash

set -e

PKGNAME=sxmlm

if [[ -z $(ocamlfind query $PKGNAME 2>&1 | grep "not found") ]]; then
    ocamlfind remove $PKGNAME
fi

ocamlbuild -use-ocamlfind -pkg xmlm -pkg ppx_sexp \
    sxmlm.cma

ocamlbuild -use-ocamlfind -pkg xmlm -pkg ppx_sexp \
    sxmlm.cmxa

ocamlfind install $PKGNAME META \
    _build/*.cmi _build/*.cma _build/*.cmxa _build/*.mli _build/*.ml
